#!/usr/bin/env bash

# Copyright (c) 2021-2025 community-scripts ORG
# Author: jaworek
# License: MIT | https://github.com/community-scripts/ProxmoxVE/raw/main/LICENSE
# Source: https://github.com/papra-hq/papra

source /dev/stdin <<<"$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

msg_info "Installing Dependencies"
$STD apt install -y \
  git \
  curl \
  build-essential \
  python3
msg_ok "Installed Dependencies"

msg_info "Setting up Node.js 24 with pnpm"
PNPM_VERSION="10.19.0"
NODE_VERSION="24" NODE_MODULE="pnpm@${PNPM_VERSION}" setup_nodejs
msg_ok "Setup Node.js 24 with pnpm ${PNPM_VERSION}"

msg_info "Installing Papra"
cd /opt
RELEASE=$(curl -fsSL https://api.github.com/repos/papra-hq/papra/releases/latest | grep "tag_name" | awk '{print substr($2, 3, length($2)-4) }')
msg_info "Installing Papra v${RELEASE} (Patience)"
curl -fsSL "https://github.com/papra-hq/papra/archive/refs/tags/v${RELEASE}.tar.gz" -o "papra-${RELEASE}.tar.gz"
$STD tar -xzf papra-${RELEASE}.tar.gz
rm -rf papra-${RELEASE}.tar.gz
mv papra-${RELEASE} papra
cd /opt/papra
msg_ok "Downloaded Papra v${RELEASE}"

msg_info "Building Papra (Patience - This Takes Time)"
export NODE_ENV=production
export COREPACK_ENABLE_DOWNLOAD_PROMPT=0
export NODE_OPTIONS="--max-old-space-size=3584"
export NEXT_PUBLIC_VERSION="v${RELEASE}"
export NEXT_PUBLIC_BUILDTIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
$STD corepack enable
$STD pnpm install --frozen-lockfile
$STD pnpm build
msg_ok "Built Papra v${RELEASE}"

msg_info "Creating Directory Structure"
mkdir -p /opt/papra/app-data/db
mkdir -p /opt/papra/app-data/documents
mkdir -p /opt/papra/ingestion
chmod -R 755 /opt/papra/app-data
msg_ok "Created Directory Structure"

msg_info "Creating Configuration File"
LOCAL_IP=$(hostname -I | awk '{print $1}')
AUTH_SECRET=$(openssl rand -hex 48)

cat <<EOF >/opt/papra/.env
# =============================================================================
# PAPRA CONFIGURATION
# =============================================================================
# Generated by ProxmoxVE Helper-Scripts
# To customize, edit this file and run: systemctl restart papra

# Environment
NODE_ENV=production
PORT=1221
SERVER_HOSTNAME=0.0.0.0

# URLs (change these to match your setup)
APP_BASE_URL=http://${LOCAL_IP}:1221
CLIENT_BASE_URL=http://${LOCAL_IP}:1221
SERVER_BASE_URL=http://${LOCAL_IP}:1221

# Authentication
AUTH_SECRET=${AUTH_SECRET}
AUTH_PROVIDERS_EMAIL_IS_ENABLED=true

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
# Default: SQLite (no additional setup required)
DATABASE_URL=file:/opt/papra/app-data/db/db.sqlite

# To switch to PostgreSQL:
# 1. Install PostgreSQL: apt install postgresql-16
# 2. Create database and user:
#    sudo -u postgres psql
#    CREATE DATABASE papra_db WITH ENCODING 'UTF8';
#    CREATE USER papra_user WITH PASSWORD 'your_password';
#    GRANT ALL PRIVILEGES ON DATABASE papra_db TO papra_user;
#    \q
# 3. Uncomment and update this line:
# DATABASE_URL=postgresql://papra_user:your_password@localhost:5432/papra_db
# 4. Comment out the SQLite DATABASE_URL above
# 5. Restart service: systemctl restart papra

# =============================================================================
# STORAGE CONFIGURATION
# =============================================================================
DOCUMENT_STORAGE_DRIVER=filesystem
DOCUMENT_STORAGE_FILESYSTEM_ROOT=/opt/papra/app-data/documents
PAPRA_CONFIG_DIR=/opt/papra/app-data

# =============================================================================
# EMAIL CONFIGURATION (Optional)
# =============================================================================
# Dry-run mode (emails logged but not sent - good for testing)
EMAILS_DRY_RUN=true

# To enable real emails, set EMAILS_DRY_RUN=false and configure SMTP:
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_USER=your-email@gmail.com
# SMTP_PASSWORD=your-app-password
# EMAILS_FROM_ADDRESS=Papra <noreply@yourdomain.com>

# =============================================================================
# ADVANCED SETTINGS
# =============================================================================
PROCESS_MODE=all
SERVER_SERVE_PUBLIC_DIR=true
BETTER_AUTH_TELEMETRY=0
EOF

chmod 600 /opt/papra/.env
msg_ok "Created Configuration File"

msg_info "Creating Service"
cat <<EOF >/etc/systemd/system/papra.service
[Unit]
Description=Papra Note-Taking and Knowledge Management
After=network.target
Documentation=https://github.com/papra-hq/papra

[Service]
Type=simple
User=root
WorkingDirectory=/opt/papra
ExecStart=/usr/bin/pnpm start:with-migrations
Restart=always
RestartSec=10
EnvironmentFile=/opt/papra/.env

# Security Hardening
PrivateTmp=true
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/opt/papra

# Resource Limits
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable -q --now papra
msg_ok "Created and Started Service"

msg_info "Saving Version Information"
echo "${RELEASE}" >/opt/papra_version.txt
msg_ok "Saved Version Information"

msg_info "Creating Credentials File"
cat <<EOF >~/papra.creds
Papra Installation Credentials
================================

Access URL: http://${LOCAL_IP}:1221

Configuration File: /opt/papra/.env
Data Directory: /opt/papra/app-data
Documents: /opt/papra/app-data/documents
Database: /opt/papra/app-data/db/db.sqlite (SQLite)
Ingestion Folder: /opt/papra/ingestion

AUTH_SECRET: ${AUTH_SECRET}

First-Time Setup:
1. Navigate to http://${LOCAL_IP}:1221
2. Create your first user account (email-based)
3. Additional users can register or be invited

Database Configuration:
- Currently using SQLite (file-based)
- To switch to PostgreSQL, see comments in /opt/papra/.env

Email Configuration:
- Currently in dry-run mode (emails logged, not sent)
- To enable real emails, configure SMTP settings in /opt/papra/.env

Ingestion Folder (Automated Document Processing):
- Disabled by default
- To enable: Add to /opt/papra/.env
  INGESTION_FOLDER_IS_ENABLED=true
  INGESTION_FOLDER_ROOT_PATH=/opt/papra/ingestion
- Place documents in /opt/papra/ingestion for automatic processing
- Configure post-processing: delete or move processed files

Useful Commands:
- View logs: journalctl -u papra -f
- Restart service: systemctl restart papra
- Check status: systemctl status papra
- Update Papra: Run the update script from Proxmox shell

For support, visit: https://github.com/papra-hq/papra
EOF

chmod 600 ~/papra.creds
msg_ok "Created Credentials File"

motd_ssh
customize
cleanup_lxc
